"""empty message

Revision ID: 1eab12082a6b
Revises: 7ce44c23e04a
Create Date: 2022-05-15 16:17:02.254591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eab12082a6b'
down_revision = '7ce44c23e04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('lore_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'lore_name')
    # ### end Alembic commands ###
