"""empty message

Revision ID: 7ce44c23e04a
Revises: b5bbc0e485fe
Create Date: 2022-05-15 15:57:26.216046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce44c23e04a'
down_revision = 'b5bbc0e485fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recruitment', sa.Float(), nullable=False),
    sa.Column('training', sa.Float(), nullable=False),
    sa.Column('attendance', sa.Float(), nullable=False),
    sa.Column('overseer', sa.Float(), nullable=False),
    sa.Column('subdivision', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strike',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('officer', sa.String(), nullable=False),
    sa.Column('receiving', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strike')
    op.drop_table('points')
    # ### end Alembic commands ###
