"""empty message

Revision ID: e52273d2d695
Revises: 
Create Date: 2022-04-27 21:27:55.968478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52273d2d695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.String(255), nullable=False),
    sa.Column('email', sa.String(255), nullable=True),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('rank', sa.String(255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
